### ISSUE TITLE
Living workshops need updating to reflect the new wiki

### ISSUE THREAD

**Issue by ctrueden** [imagej/presentations#9]
The new wiki has changed some things, so these workshops need corresponding updates:

* The ImageJ logo was updated.
* The look of the wiki has changed, so screenshots should be redone.
* The new wiki has its own search bar now, which should be covered in the intro workshop.
* And probably other things; keep an eye out for outdated content on the slides.

**Comment by etadobson** [comment]
The workshops have been updated accordingly... however, they are not *live* at the moment.  There is an issue with the current link in the wiki.  @elevans would you be able to help me fix the living workshop section of the events\presentations page a bit?

**Comment by ctrueden** [comment]
What do you mean by "have been updated"? Where are the commits? I checked https://github.com/imagej/presentations and I don't see anything new.

**Comment by ctrueden** [comment]
With imagej/imagej.github.io@d413f7d7cff6526937974600f8a76adde5efbfc8, the tables on the events/presentation page are fixed. The slides here still need updating, though.

**Comment by etadobson** [comment]
I made the changes/commits but couldn't push to remote for whatever reason... I also updated the Living Workshop table - that old image needs to go away.  But again - I couldn't push.

**Comment by ctrueden** [comment]
> for whatever reason

More details, please. Which repo? imagej/presentations or imagej/imagej.github.io, or both? Copy/paste the error message(s). We'll figure it out. We can also do a video call if you're stuck.

**Comment by etadobson** [comment]
I'm assuming if I make changes to the wiki - any page - I need to push to imagej/imagej.github.io - which is what I was trying to do.  I will pull your new changes and try again... if I have trouble - will ping you.  Thanks!

**Comment by etadobson** [comment]
I fixed my issue... was:

```
fatal: remote error: 
  You can't push to git://github.com/imagej/imagej.github.io.git
  Use https://github.com/imagej/imagej.github.io.git
```
so I ...

```
git remote set-url origin https://github.com/imagej/imagej.github.io.git
```
now it's working for me...

**Comment by etadobson** [comment]
Links to updated Introduction and Segmentation workshops have been included... https://github.com/imagej/imagej.github.io/commit/06f7bd5243aedabdb654b8978c0a8ea311bcdaea

**Comment by etadobson** [comment]
All workshops have been updated and linked (https://imagej.net/events/presentations#living-workshops) ... including scripting (https://github.com/imagej/imagej.github.io/commit/65cdc5a59f52b5c7a7b9b71247607ded84917aaa).
